catalog/urls.py
from django.urls import path
from .views import index, BookListView,BookDetailView,AuthorDetailView,AuthorListView,BBLoginView,BBLogoutView,AuthorCreate,AuthorUpdate,AuthorDelete

app_name = 'catalog'

urlpatterns = [
    path('', index, name='index'),
    path('account/login', BBLoginView.as_view(),name='login'),
    path('account/logout', BBLogoutView.as_view(),name='logout'),
    path('books/', BookListView.as_view(), name='books'), 
    path('book/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('authors/',AuthorListView.as_view(),name='authors'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

catalog/models.py
from django.db import models
from django.urls import reverse  #Используется для генерации URL-адресов путем изменения шаблонов URL-адресов

import uuid # Required for unique book instances

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    class Meta:
        ordering = ['last_name']



class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        return '%s (%s)' % (self.id,self.book.title)



class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g., Science Fiction, French Poetry, etc.)",
        verbose_name='Название жанра'
    )

    class Meta:
        ordering = ['name']  # Order genres alphabetically by name
        verbose_name = 'Жанр'  # Singular form for admin
        verbose_name_plural = 'Жанры'  # Plural form for admin

    def __str__(self):
        return self.name
    
    

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    RATING_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]

    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, null=True, blank=True,
                                               help_text="Rate this book from 1 to 5")

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('catalog:book-detail', args=[self.pk])

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Author


def index(request):
    # Генерация "количеств" некоторых главных объектов
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Доступные книги (статус = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # Метод 'all()' применён по умолчанию.

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'main/index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors},
    )
class BBLoginView(LoginView):
    template_name = 'user/login.html'

class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'user/logged_out.html'

class BookListView(generic.ListView):
    model = Book
    template_name = 'books/book_list.html'
    context_object_name = 'book_list' 

    def get_queryset(self):
        queryset = super().get_queryset()
        rating_filter = self.request.GET.get('rating')

        if rating_filter:
            queryset = queryset.filter(rating=rating_filter)

        return queryset.order_by('-rating')

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'books/book_detail.html' 

    def book_detail_view(request,pk):
        try:
            book_id=Book.objects.get(pk=pk)
        except Book.DoesNotExist:
            raise Http404("Book does not exist")
        return render(
            request,
            'books/book_detail.html',
            context={'book':book_id,}
        )


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'authors/author.html'


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'authors/author_detail.html'
    context_object_name = 'author'  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_list'] = Book.objects.filter(author=self.object)  # Получаем книги данного автора
        return context
    

class LibrarianRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.groups.filter(name='Librarians').exists()

class AuthorCreate(LoginRequiredMixin, LibrarianRequiredMixin,CreateView):
    model = Author
    fields = '__all__'
    template_name = 'authors/author_form.html'
    initial = {'date_of_death': '12/10/2016',}

class AuthorUpdate(LoginRequiredMixin, LibrarianRequiredMixin,UpdateView):
    model = Author
    template_name = 'authors/author_form.html'
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(LoginRequiredMixin, LibrarianRequiredMixin,DeleteView):
    model = Author
    template_name = 'authors/author_confirm_delete.html'
    success_url = reverse_lazy('catalog:authors')  

catalog/templates/authors/author.html
{% extends "layout/base.html" %}

{% block content %}
    <h1>Список авторов</h1>

    {% if author_list %}
    <ul>
        {% for author in author_list %}
        <li>
            <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
      <p>В библиотеке нет авторов.</p>
    {% endif %}
{% endblock %}

catalog/templates/authors/author_confirm_delete.html
{% extends "layout/base.html" %}

{% block content %}
  <h1>Delete Author</h1>

  <p>Are you sure you want to delete the author: {{ author }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
  </form>
{% endblock %}

catalog/templates/authors/author_detail.html
{% extends "layout/base.html" %}

{% block content %}
  <h2>Автор</h2>
  <p><strong>Имя:</strong>{{ author.first_name }}</p>
  <p><strong>Фамилия:</strong>{{ author.last_name }}</p>
  <p><strong>Дата рождения:</strong>{{ author.date_of_birth }}</p>
  <p><strong>Дата смерти:</strong>{{ author.date_of_death }}</p>
  {% if book_list %}
  <h3>Книги автора:</h3>
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>У этого автора нет книг в библиотеке.</p>
  {% endif %}
{% endblock %}

catalog/templates/authors/author_form.html
{% extends "layout/base.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/books/book_detail.html
{% extends "layout/base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/books/book_list.html
{% extends "layout/base.html" %}

{% block content %}
<h1>Список книг</h1>
<p>Всего книг: {{ book_list.count }}</p>

<h2>Фильтр книг по рейтингу</h2>
<form method="get" action="{% url 'catalog:books' %}">
  <label for="rating">Выберите рейтинг:</label>
  <select name="rating" id="rating">
      <option value="">Все рейтинги</option>
      {% for i in "12345" %}
          <option value="{{ i }}" {% if request.GET.rating == i %}selected{% endif %}>{{ i }}</option>
      {% endfor %}
  </select>
  <button type="submit">Фильтровать</button>
</form>

{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }}) - Рейтинг: {{ book.rating }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Книги с выбранным рейтингом не найдены.</p> 
{% endif %}
{% endblock %}

catalog/templates/books/book_renew_librarian.html
{% extends "layout/base.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/layout/base.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'catalog:index' %}">Home</a></li>
              <li><a href="{% url 'catalog:books' %}">All books</a></li>
              <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
            {% if user.is_authenticated %}
              <li>User: {{ user.get_username }}</li>
              <li> 
                <form method="post" action="{% url 'catalog:logout' %}">
                {% csrf_token %}
                <button type="submit" class="">Logout</button>
              </form>
            </li>
            {% else %}
              <li>
                <form method="post" action="{% url 'catalog:login' %}">
                  {% csrf_token %}
                  <button type="submit" class="">Login</button>
                </form>
              </li>
            {% endif %}
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

catalog/templates/main/index.html
{% extends "layout/base.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}

catalog/templates/user/logged_out.html
{% extends "layout/base.html" %}

{% block content %}
  <p>Logged out!</p>

  <a href="{% url 'catalog:login'%}">Click here to login again.</a>
{% endblock %}

catalog/templates/user/login.html
{% extends "layout/base.html" %}

{% block content %}

{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

<form method="post" action="{% url 'catalog:login' %}">
{% csrf_token %}
{{ form.as_p }}  
<input type="submit" value="Login" />
</form>

{% endblock %}

catalog/templates/user/password_reset_complete.html
{% extends "layout/base.html" %}

{% block content %}
  <h1>The password has been changed!</h1>
  <p><a href="{% url 'catalog:login' %}">log in again?</a></p>
{% endblock %}

catalog/templates/user/password_reset_confirm.html
{% extends "layout/base.html" %}

{% block content %}
  {% if validlink %}
    <p>Please enter (and confirm) your new password.</p>
    <form action="" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td>
            {{ form.new_password1.errors }}
            <label for="id_new_password1">New password:</label>
          </td>
          <td>{{ form.new_password1 }}</td>
        </tr>
        <tr>
          <td>
            {{ form.new_password2.errors }}
            <label for="id_new_password2">Confirm password:</label>
          </td>
          <td>{{ form.new_password2 }}</td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" value="Change my password" /></td>
        </tr>
      </table>
    </form>
  {% else %}
    <h1>Password reset failed</h1>
    <p>
      The password reset link was invalid, possibly because it has already been
      used. Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

catalog/templates/user/password_reset_done.html
{% extends "layot/base.html" %}

{% block content %}
  <p>
    We've emailed you instructions for setting your password. If they haven't
    arrived in a few minutes, check your spam folder.
  </p>
{% endblock %}

catalog/templates/user/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'catalog:password_reset_confirm' uidb64=uid token=token %}

catalog/templates/user/password_reset_form.html
{% extends "layout/base.html" %}

{% block content %}
  <h2>Reset Your Password</h2>
  <form action="" method="post">{% csrf_token %}
      {% if form.email.errors %}
          <div class="alert alert-danger">
              {{ form.email.errors }}
          </div>
      {% endif %}
      <p>{{ form.email.label }}: {{  form.username }}</p>
      <input type="submit" class="btn btn-default btn-lg" value="Reset password" />
  </form>
{% endblock %}